functionsDirectory = "C:\\job\\blog\\netlify\\functions"
functionsDirectoryOrigin = "config"
plugins = []
headers = []
redirects = []

[build]
publish = "C:\\job\\blog\\_deploy\\public"
publishOrigin = "config"
commandOrigin = "config"
command = "pip install -r requirements.txt && python build.py"
functions = "C:\\job\\blog\\netlify\\functions"

[build.environment]
PYTHON_VERSION = "3.11"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]
node_bundler = "esbuild"